services:
  - type: web
    name: streamlit-langgraph-chatbot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_frontend_tool.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: GOOGLE_API_KEY
        sync: false
      - key: LANGCHAIN_TRACING_V2
        value: "true"
      - key: LANGCHAIN_ENDPOINT
        value: https://api.smith.langchain.com
      - key: LANGCHAIN_API_KEY
        sync: false
      - key: LANGCHAIN_PROJECT
        value: Chatbot Project
